apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  labels:
    run: kubia
spec:
  replicas: 3
  selector:
    run: kubia
  template:
    metadata:
      labels:
        run: kubia
    spec:
      containers:
        - name: kubia
          image: knix008/kubia:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
