apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
  labels:
    apps: jobs
spec:
  template:
    metadata:
      labels:
        apps: jobs
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:1
          imagePullPolicy: Always
          args:
            - "--keygen-enable"
            - "--keygen-exit-on-complete"
            - "--keygen-num-to-gen=10"
            - "--keygen-exit-code=1"
      restartPolicy: OnFailure