apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyter
  name: jupyter
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - image: jupyter/scipy-notebook
          name: jupyter
