apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
    - image: knix008/kuard-shkwon-amd64:1.0
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP