apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
        version: "1"
    spec:
      containers:
        - name: kuard
          image: "knix008/kuard-shkwon-amd64:1.0"