apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
        - name: helloworld
          image: kelseyhightower/helloworld:v1
          ports:
          - containerPort: 80